In [1]:
import numpy as np

In [2]:
l= [1,2,3,4]

In [4]:
ar = np.array(l) #array is super class in case of numpy

In [5]:
ar

array([1, 2, 3, 4])

In [6]:
type(ar)

numpy.ndarray

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a=[2,3,4]

In [10]:
np.asanyarray(a)

array([2, 3, 4])

In [11]:
b = np.matrix(l) #matrix is subset of array, it is by deafult 2d

In [12]:
b

matrix([[1, 2, 3, 4]])

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
a= np.array(l)

In [15]:
c= a #pointing the same variable and the changes are done in same place called swallow copy

In [16]:
c

array([1, 2, 3, 4])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
c[0]

1

In [19]:
c[0]=100

In [20]:
c

array([100,   2,   3,   4])

In [21]:
a

array([100,   2,   3,   4])

In [22]:
d = np.copy(a) # here copy the data in new location not in same place called Deep copy

In [23]:
d

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
a[1] = 400

In [26]:
a

array([100, 400,   3,   4])

In [27]:
d 

array([100,   2,   3,   4])

In [28]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [35]:
iterable=(i*i for i in range(5))

In [36]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [37]:
np.fromstring('234 234', sep = ' ')

array([234., 234.])

In [38]:
np.fromstring('4,5', sep = ' ,')

array([4., 5.])

In [ ]:
#numpy Data types

In [39]:
l = [2,3,4,5]

In [40]:
ar = np.array(l)

In [41]:
ar

array([2, 3, 4, 5])

In [42]:
ar.ndim

1

In [43]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [44]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [45]:
ar2.ndim

2

In [46]:
ar.size

4

In [47]:
ar2.size

8

In [48]:
ar.shape

(4,)

In [49]:
ar2.shape

(2, 4)

In [50]:
ar.dtype

dtype('int32')

In [51]:
ar2.dtype

dtype('int32')

In [52]:
ar22 = np.array([(1.4,4,45),(23,45,32)])

In [53]:
ar22

array([[ 1.4,  4. , 45. ],
       [23. , 45. , 32. ]])

In [54]:
ar22.dtype

dtype('float64')

In [56]:
list(range(5)) #range not take floating value

[0, 1, 2, 3, 4]

In [58]:
np.arange(2.3, 4.5)

array([2.3, 3.3, 4.3])

In [59]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [60]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [61]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.zeros((3,4,2)) #first index how many axis and second and third is row and col

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [64]:
np.zeros((3,4,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [67]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [68]:
np.ones((3,4,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [69]:
on = np.ones((2,2))

In [70]:
on+5

array([[6., 6.],
       [6., 6.]])

In [71]:
on*4

array([[4., 4.],
       [4., 4.]])

In [73]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [74]:
np.eye(4) #identiy matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [76]:
np.logspace(2,5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [77]:
np.logspace(2,5, 10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [80]:
ar=np.random.randn(3,4) #produce random data having mean is 0 and std is 1.called standard normal distribution

In [79]:
import pandas as pd

In [81]:
pd.DataFrame(ar)

0         1         2         3
0 -0.057139  1.566388  0.838707  1.181814
1  1.941077  0.675894 -0.229914 -0.374503
2  1.434862  1.932288  0.032674  0.585543

In [82]:
np.random.rand(3,4) #it produce normally like randomly int value

array([[0.8419391 , 0.43882358, 0.27318488, 0.36368048],
       [0.42861009, 0.92123512, 0.92380025, 0.32248662],
       [0.94722542, 0.66637944, 0.9884117 , 0.14765719]])

In [84]:
pd.DataFrame(np.random.randint(1,10,(3,4)) )#produce int value

0  1  2  3
0  5  3  3  7
1  9  9  4  3
2  6  3  4  3

In [85]:
ar

array([[-0.0571387 ,  1.56638808,  0.83870663,  1.18181359],
       [ 1.94107673,  0.67589376, -0.22991351, -0.37450344],
       [ 1.43486168,  1.93228816,  0.03267398,  0.5855426 ]])

In [92]:
arr1 = ar.reshape(6,2) #reshape the same array

In [93]:
arr1

array([[-0.0571387 ,  1.56638808],
       [ 0.83870663,  1.18181359],
       [ 1.94107673,  0.67589376],
       [-0.22991351, -0.37450344],
       [ 1.43486168,  1.93228816],
       [ 0.03267398,  0.5855426 ]])

In [95]:
arr1[1][1]

1.1818135872523274

In [97]:
arr1[2:5,1]

array([ 0.67589376, -0.37450344,  1.93228816])

In [99]:
arr = np.random.randint(1,100, (5,5))

In [100]:
arr

array([[12, 69, 16, 98, 27],
       [94, 71, 41, 31, 65],
       [77, 63, 51, 66, 40],
       [ 5, 76, 86, 40,  3],
       [56, 30, 57, 94, 40]])

In [101]:
arr>50

array([[False,  True, False,  True, False],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True, False, False],
       [ True, False,  True,  True, False]])

In [102]:
arr[arr>50]

array([69, 98, 94, 71, 65, 77, 63, 51, 66, 76, 86, 56, 57, 94])

In [103]:
arr

array([[12, 69, 16, 98, 27],
       [94, 71, 41, 31, 65],
       [77, 63, 51, 66, 40],
       [ 5, 76, 86, 40,  3],
       [56, 30, 57, 94, 40]])

In [105]:
arr[2:4,[1,2]]

array([[63, 51],
       [76, 86]])

In [106]:
arr[0][0]

12

In [107]:
arr[0][0]=200

In [108]:
arr

array([[200,  69,  16,  98,  27],
       [ 94,  71,  41,  31,  65],
       [ 77,  63,  51,  66,  40],
       [  5,  76,  86,  40,   3],
       [ 56,  30,  57,  94,  40]])

In [109]:
arr1 = np.random.randint(1,3,(3,3))

In [110]:
arr2 = np.random.randint(1,3,(3,3))

In [111]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [112]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [1, 2, 2]])

In [113]:
arr1+arr2

array([[2, 2, 3],
       [2, 3, 2],
       [2, 3, 4]])

In [114]:
arr1*arr2 #simple index wise multiplication

array([[1, 1, 2],
       [1, 2, 1],
       [1, 2, 4]])

In [115]:
arr1-arr2

array([[ 0,  0,  1],
       [ 0, -1,  0],
       [ 0, -1,  0]])

In [116]:
arr1/arr2

array([[1. , 1. , 2. ],
       [1. , 0.5, 1. ],
       [1. , 0.5, 1. ]])

In [117]:
arr1@arr2#matrix multiplication

array([[4, 7, 6],
       [3, 5, 4],
       [4, 7, 6]])

In [118]:
arr1/0

C:\Users\hp\AppData\Local\Temp\ipykernel_17456\1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [119]:
arr1

array([[1, 1, 2],
       [1, 1, 1],
       [1, 1, 2]])

In [120]:
arr1+100

array([[101, 101, 102],
       [101, 101, 101],
       [101, 101, 102]])

In [121]:
arr1**2

array([[1, 1, 4],
       [1, 1, 1],
       [1, 1, 4]])

In [ ]:
#numpy- broadcasting

In [122]:
arr = np.zeros((4,4))

In [123]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
row = np.array([1,2,3,4])

In [125]:
row

array([1, 2, 3, 4])

In [126]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [127]:
row.T

array([1, 2, 3, 4])

In [128]:
arr.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [129]:
col = np.array([[1,2,3,4]])

In [130]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [131]:
col

array([[1, 2, 3, 4]])

In [133]:
arr+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [135]:
arr1=np.random.randint(1,4,(3,4))

In [136]:
arr1

array([[3, 2, 1, 2],
       [2, 1, 2, 1],
       [3, 2, 2, 1]])

In [137]:
np.sqrt(arr1)

array([[1.73205081, 1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356, 1.        ],
       [1.73205081, 1.41421356, 1.41421356, 1.        ]])

In [138]:
np.exp(arr1)

array([[20.08553692,  7.3890561 ,  2.71828183,  7.3890561 ],
       [ 7.3890561 ,  2.71828183,  7.3890561 ,  2.71828183],
       [20.08553692,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [139]:
np.log10(arr1)

array([[0.47712125, 0.30103   , 0.        , 0.30103   ],
       [0.30103   , 0.        , 0.30103   , 0.        ],
       [0.47712125, 0.30103   , 0.30103   , 0.        ]])

In [ ]:
#numpy - array manipulation

In [140]:
arr = np.random.randint(1,10,(3,4))

In [141]:
arr

array([[1, 8, 1, 5],
       [3, 3, 7, 7],
       [4, 9, 2, 8]])

In [142]:
arr.reshape(6,2)

array([[1, 8],
       [1, 5],
       [3, 3],
       [7, 7],
       [4, 9],
       [2, 8]])

In [143]:
arr.reshape(7,7) #cannot reshape because dimension are not compatible

ValueError: cannot reshape array of size 12 into shape (7,7)

In [144]:
arr.flatten() #convert 2d to 1d

array([1, 8, 1, 5, 3, 3, 7, 7, 4, 9, 2, 8])

In [145]:
arr1 = np.array([1,2,3,4,5])

In [146]:
arr1.ndim

1

In [147]:
np.expand_dims(arr1, axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [148]:
np.expand_dims(arr1, axis = 0)

array([[1, 2, 3, 4, 5]])

In [149]:
arr

array([[1, 8, 1, 5],
       [3, 3, 7, 7],
       [4, 9, 2, 8]])

In [150]:
np.squeeze(arr)

array([[1, 8, 1, 5],
       [3, 3, 7, 7],
       [4, 9, 2, 8]])

In [151]:
data = np.array([[1],[2],[3]])

In [152]:
data

array([[1],
       [2],
       [3]])

In [153]:
np.squeeze(data)

array([1, 2, 3])

In [154]:
arr1

array([1, 2, 3, 4, 5])

In [155]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [156]:
np.roll(arr1, 2) #shift the 2 place from curr index

array([4, 5, 1, 2, 3])

In [157]:
np.diag(arr1) #print data diagonally

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [ ]:
#numpy- Binary operation

In [158]:
arr1 = np.random.randint(1, 10, (3,4))

In [159]:
arr2 = np.random.randint(1,10,(3,4))

In [160]:
arr1

array([[2, 9, 9, 6],
       [2, 9, 9, 6],
       [7, 2, 9, 6]])

In [161]:
arr2

array([[8, 8, 2, 2],
       [5, 1, 9, 7],
       [1, 6, 4, 1]])

In [162]:
arr1 + arr2

array([[10, 17, 11,  8],
       [ 7, 10, 18, 13],
       [ 8,  8, 13,  7]])

In [163]:
arr1 * arr2

array([[16, 72, 18, 12],
       [10,  9, 81, 42],
       [ 7, 12, 36,  6]])

In [164]:
arr1 /arr2

array([[0.25      , 1.125     , 4.5       , 3.        ],
       [0.4       , 9.        , 1.        , 0.85714286],
       [7.        , 0.33333333, 2.25      , 6.        ]])

In [165]:
arr1-arr2

array([[-6,  1,  7,  4],
       [-3,  8,  0, -1],
       [ 6, -4,  5,  5]])

In [166]:
arr1%arr2

array([[2, 1, 1, 0],
       [2, 0, 0, 6],
       [0, 2, 1, 0]])

In [167]:
arr1**arr2

array([[      256,  43046721,        81,        36],
       [       32,         9, 387420489,    279936],
       [        7,        64,      6561,         6]])

In [168]:
arr1 & arr2

array([[0, 8, 0, 2],
       [0, 1, 9, 6],
       [1, 2, 0, 0]])

In [169]:
arr1

array([[2, 9, 9, 6],
       [2, 9, 9, 6],
       [7, 2, 9, 6]])

In [170]:
arr2

array([[8, 8, 2, 2],
       [5, 1, 9, 7],
       [1, 6, 4, 1]])

In [171]:
~arr1

array([[ -3, -10, -10,  -7],
       [ -3, -10, -10,  -7],
       [ -8,  -3, -10,  -7]])

In [172]:
arr1 | arr2

array([[10,  9, 11,  6],
       [ 7,  9,  9,  7],
       [ 7,  6, 13,  7]])

In [175]:
arr1 > arr2

array([[False,  True,  True,  True],
       [False,  True, False, False],
       [ True, False,  True,  True]])

In [174]:
arr1 == arr2

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [ ]:
#numpy- string function

In [176]:
arr = np.array(['rohit','kumar'])

In [177]:
arr

array(['rohit', 'kumar'], dtype='<U5')

In [178]:
np.char.upper(arr)

array(['ROHIT', 'KUMAR'], dtype='<U5')

In [179]:
np.char.title(arr)

array(['Rohit', 'Kumar'], dtype='<U5')

In [180]:
np.char.capitalize(arr)

array(['Rohit', 'Kumar'], dtype='<U5')

In [ ]:
#numpy - mathematical function

In [181]:
arr1

array([[2, 9, 9, 6],
       [2, 9, 9, 6],
       [7, 2, 9, 6]])

In [182]:
np.sin(arr1)

array([[ 0.90929743,  0.41211849,  0.41211849, -0.2794155 ],
       [ 0.90929743,  0.41211849,  0.41211849, -0.2794155 ],
       [ 0.6569866 ,  0.90929743,  0.41211849, -0.2794155 ]])

In [183]:
np.cos(arr1)

array([[-0.41614684, -0.91113026, -0.91113026,  0.96017029],
       [-0.41614684, -0.91113026, -0.91113026,  0.96017029],
       [ 0.75390225, -0.41614684, -0.91113026,  0.96017029]])

In [184]:
np.tan(arr1)

array([[-2.18503986, -0.45231566, -0.45231566, -0.29100619],
       [-2.18503986, -0.45231566, -0.45231566, -0.29100619],
       [ 0.87144798, -2.18503986, -0.45231566, -0.29100619]])

In [185]:
np.tanh(arr1)  #hypertangent

array([[0.96402758, 0.99999997, 0.99999997, 0.99998771],
       [0.96402758, 0.99999997, 0.99999997, 0.99998771],
       [0.99999834, 0.96402758, 0.99999997, 0.99998771]])

In [186]:
np.log10(arr1)

array([[0.30103   , 0.95424251, 0.95424251, 0.77815125],
       [0.30103   , 0.95424251, 0.95424251, 0.77815125],
       [0.84509804, 0.30103   , 0.95424251, 0.77815125]])

In [187]:
np.exp(arr1)

array([[7.38905610e+00, 8.10308393e+03, 8.10308393e+03, 4.03428793e+02],
       [7.38905610e+00, 8.10308393e+03, 8.10308393e+03, 4.03428793e+02],
       [1.09663316e+03, 7.38905610e+00, 8.10308393e+03, 4.03428793e+02]])

In [188]:
np.sqrt(arr1)

array([[1.41421356, 3.        , 3.        , 2.44948974],
       [1.41421356, 3.        , 3.        , 2.44948974],
       [2.64575131, 1.41421356, 3.        , 2.44948974]])

In [189]:
np.power(arr1,2)

array([[ 4, 81, 81, 36],
       [ 4, 81, 81, 36],
       [49,  4, 81, 36]], dtype=int32)

In [190]:
np.mean(arr1)

6.333333333333333

In [191]:
np.median(arr1)

6.5

In [192]:
np.std(arr1)

2.778888666755511

In [193]:
np.var(arr1)

7.722222222222221

In [194]:
np.min(arr1)

2

In [195]:
np.max(arr1)

9

In [ ]:
#sort searching and counting function

In [196]:
arr = np.array([4,2,5,6,4,3,2,1,5,6,78,5])

In [197]:
np.sort(arr)

array([ 1,  2,  2,  3,  4,  4,  5,  5,  5,  6,  6, 78])

In [199]:
np.searchsorted(arr, 34)

12

In [200]:
arr1 = np.array([0,345,234,654,67,76,45,34,23,21])

In [201]:
np.count_nonzero(arr1)

9

In [203]:
np.where(arr1 > 6)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [206]:
np.extract(arr1>3, arr)

array([2, 5, 6, 4, 3, 2, 1, 5, 6])

In [ ]:
#numpy - byte swapping

In [207]:
arr1.byteswap()

array([          0,  1493237760,  -369098752, -1912471552,  1124073472,
        1275068416,   754974720,   570425344,   385875968,   352321536])

In [ ]:
#numpy - Copies & views

In [208]:
a = np.copy(arr)

In [209]:
a

array([ 4,  2,  5,  6,  4,  3,  2,  1,  5,  6, 78,  5])

In [211]:
b = arr.view()  #not allocate new place refer into same place

In [212]:
b

array([ 4,  2,  5,  6,  4,  3,  2,  1,  5,  6, 78,  5])

In [ ]:
#numpy - matrix library

In [213]:
import numpy.matlib as nm

In [214]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [215]:
nm.ones(5)

matrix([[1., 1., 1., 1., 1.]])

In [216]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [217]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#numpy- linear algebra

In [218]:
arr1 = np.random.randint([[2,3],[4,5]])

In [219]:
arr2 = np.random.randint([[2,3],[4,5]])

In [220]:
np.dot(arr1, arr2)

array([[5, 8],
       [6, 9]])

In [221]:
arr1@arr2

array([[5, 8],
       [6, 9]])